export const SAVE_NEWS_CARD = "SAVED-NEWS/SAVE_NEWS_CARD";
export const FETCH_NEWS_CARDS = "NEWS/FETCH_NEWS_CARDS";
export const REMOVE_NEWS_CARD = "NEWS/REMOVE_NEWS_CARD";
export const GET_SAVED_CARDS = "SAVED-NEWS/GET_SAVED_CARDS";
export const SET_KEYWORD = "NEWS/SET_KEYWORD";
export const SET_BOOKMARKED = "NEWS/SET_BOOKMARKED";
export const REMOVE_BOOKMARKED = "NEWS/REMOVE_BOOKMARKED";
export const START_SEARCH = "APP/START_SEARCH";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SET_TOKEN = "APP/SET_TOKEN";
export const LOGIN_TRUE = "APP/LOGIN_TRUE";
export const LOGIN_FALSE = "APP/LOGIN_FALSE";
export const REMOVE_TOKEN = "APP/REMOVE_TOKEN";

export const SET_POPUP_OPEN = "APP/SET_POPUP_OPEN";
export const SET_POPUP_CLOSE = "APP/SET_POPUP_CLOSE";
export const SET_INFO_POPUP_OPEN = "APP/SET_INFO_POPUP_OPEN";
export const SET_INFO_POPUP_CLOSE = "APP/SET_POPUP_CLOSE";

export const SET_MESSAGE_TRUE = "APP/SET_MESSAGE_TRUE";
export const SET_MESSAGE_FALSE = "APP/SET_MESSAGE_FALSE";

export const SET_USER_INFORMATION = "USER/SET_USER_INFORMATION";
